# Generated by hand for the initial schema.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("prompt", models.TextField()),
                ("genre", models.CharField(
                    choices=[
                        ("pop", "Pop"), ("rock", "Rock"), ("jazz", "Jazz"),
                        ("classical", "Classical"), ("hiphop", "Hip-Hop"),
                        ("electronic", "Electronic"), ("lofi", "Lo-Fi"),
                        ("ambient", "Ambient"),
                    ], default="pop", max_length=20,
                )),
                ("audio_file", models.FileField(blank=True, null=True, upload_to="songs/")),
                ("audio_url", models.URLField(blank=True)),
                ("strategy_used", models.CharField(default="mock", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="songs",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
